version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Logging in to CodeArtifact...
      - aws codeartifact login --tool npm --domain mydomain --domain-owner 481716204214 --repository mynpmrepo
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running tests...
      - npm test  # <-- Yahan test command chalegi
  build:
    commands:
      - echo Build started...
      - echo Creating package...
      - npm pack
      - pwd
      - ls
      - echo Publishing to CodeArtifact....
      - npm version patch  # <-- ye auto version bump karega
      - cat package.json
      - npm publish
  post_build:
    commands:
      - echo Build completed
      - ls
      - pwd
artifacts:
  files:
    - '**/*'
