version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Logging in to CodeArtifact...
      - aws codeartifact login --tool npm --domain mydomain --domain-owner 481716204214 --repository mynpmrepo
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
